@startuml

title 가카헌정 다이어그램 <b>나는꼼수다 총정리</b>

:이명박: .r.> :오세훈:		: 후계자
:이명박: --> :홍준표:		: 달래기
:홍준표: -u-> :오세훈:		: 의가상함
:이명박: -d-> :김정일:		: 관계회복
:이명박: -d-> :검찰:		: 가카는 이러실 분이 아닙니다
:이명박: -l-> :법무법인 바른:
:법무법인 바른: -l-> :박교수:	: 비호회유
:검찰: -d-> :박교수:		: 압박
:검찰: -d-> :언론:		: 수사 생중계
:언론: -l-> :야당:		: 압박
:야당: -l-> :곽노현:		: 사퇴종용
:박교수: -l-> :곽노현:		: 물고늘어지기\n가짜각서 가짜녹취

note "<b>선물보따리</b>\n가스관 개통 연간1억불\n내년 정상회담?\n긴장완화 대북지원" as GIFT1

GIFT1 .u.> :김정일:
:홍준표: ..> GIFT1		: 입방정
:이명박: ..> GIFT1		: 자원외교\n치적쌓기

@enduml
